env:
  JSONNET_PATH: ../vendor
tasks:
  taskfile:gen:
    cmds:
    - jsonnet {{.JSONNET_INPUT_FILE}} | dasel -f - -r json -w yaml --pretty > '{{.OUTPUT_FILE}}'
    run: once
    vars:
      JSONNET_INPUT_FILE: taskfile_test.jsonnet
      OUTPUT_FILE: Taskfile.yml
version: "3"
